// Date: 11/7/2014 2:34:33 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.caske2000.carnivores.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBullet extends ModelBase
{
  //fields
    ModelRenderer bullet;
  
  public ModelBullet()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      bullet = new ModelRenderer(this, 0, 0);
      bullet.addBox(0F, 0F, 0F, 1, 1, 1);
      bullet.setRotationPoint(0F, 0F, 0F);
      bullet.setTextureSize(32, 32);
      bullet.mirror = true;
      setRotation(bullet, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    bullet.render(f5);
  }
  
  public void renderModel(float f)
  {
	  bullet.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
